// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAPI.Data;

#nullable disable

namespace StudentAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727130504_SeedStudents")]
    partial class SeedStudents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EnrollDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Lahore",
                            Course = "BSIT",
                            Email = "abdullah@student.com",
                            EnrollDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.9500000000000002,
                            IsActive = true,
                            Name = "Abdullah Imran"
                        },
                        new
                        {
                            Id = 2,
                            City = "Karachi",
                            Course = "BSCS",
                            Email = "ali@student.com",
                            EnrollDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.7000000000000002,
                            IsActive = true,
                            Name = "Ali Hassan"
                        },
                        new
                        {
                            Id = 3,
                            City = "Lahore",
                            Course = "BSIT",
                            Email = "sara@student.com",
                            EnrollDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.8500000000000001,
                            IsActive = true,
                            Name = "Sara Khan"
                        },
                        new
                        {
                            Id = 4,
                            City = "Islamabad",
                            Course = "BBA",
                            Email = "usman@student.com",
                            EnrollDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.6000000000000001,
                            IsActive = true,
                            Name = "Usman Malik"
                        },
                        new
                        {
                            Id = 5,
                            City = "Karachi",
                            Course = "BSCS",
                            Email = "ayesha@student.com",
                            EnrollDate = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.8999999999999999,
                            IsActive = true,
                            Name = "Ayesha Siddiqui"
                        },
                        new
                        {
                            Id = 6,
                            City = "Multan",
                            Course = "BSIT",
                            Email = "bilal@student.com",
                            EnrollDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.3999999999999999,
                            IsActive = true,
                            Name = "Bilal Ahmed"
                        },
                        new
                        {
                            Id = 7,
                            City = "Faisalabad",
                            Course = "BSCS",
                            Email = "fatima@student.com",
                            EnrollDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.5499999999999998,
                            IsActive = true,
                            Name = "Fatima Noor"
                        },
                        new
                        {
                            Id = 8,
                            City = "Rawalpindi",
                            Course = "BSIT",
                            Email = "hamza@student.com",
                            EnrollDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.7999999999999998,
                            IsActive = true,
                            Name = "Hamza Ali"
                        },
                        new
                        {
                            Id = 9,
                            City = "Peshawar",
                            Course = "BBA",
                            Email = "zara@student.com",
                            EnrollDate = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.1000000000000001,
                            IsActive = true,
                            Name = "Zara Ahmed"
                        },
                        new
                        {
                            Id = 10,
                            City = "Quetta",
                            Course = "BSIT",
                            Email = "omar@student.com",
                            EnrollDate = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.3999999999999999,
                            IsActive = true,
                            Name = "Omar Farooq"
                        },
                        new
                        {
                            Id = 11,
                            City = "Lahore",
                            Course = "BSCS",
                            Email = "hina@student.com",
                            EnrollDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.8999999999999999,
                            IsActive = true,
                            Name = "Hina Rizvi"
                        },
                        new
                        {
                            Id = 12,
                            City = "Karachi",
                            Course = "BSIT",
                            Email = "rayan@student.com",
                            EnrollDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.2000000000000002,
                            IsActive = true,
                            Name = "Rayan Khan"
                        },
                        new
                        {
                            Id = 13,
                            City = "Islamabad",
                            Course = "BBA",
                            Email = "mahnoor@student.com",
                            EnrollDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.1000000000000001,
                            IsActive = true,
                            Name = "Mahnoor Sheikh"
                        },
                        new
                        {
                            Id = 14,
                            City = "Multan",
                            Course = "BSCS",
                            Email = "zain@student.com",
                            EnrollDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.2999999999999998,
                            IsActive = true,
                            Name = "Zain Abbas"
                        },
                        new
                        {
                            Id = 15,
                            City = "Faisalabad",
                            Course = "BSIT",
                            Email = "sana@student.com",
                            EnrollDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.7000000000000002,
                            IsActive = true,
                            Name = "Sana Tariq"
                        },
                        new
                        {
                            Id = 16,
                            City = "Rawalpindi",
                            Course = "BBA",
                            Email = "adeel@student.com",
                            EnrollDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.5800000000000001,
                            IsActive = true,
                            Name = "Adeel Hussain"
                        },
                        new
                        {
                            Id = 17,
                            City = "Peshawar",
                            Course = "BSIT",
                            Email = "nadia@student.com",
                            EnrollDate = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.5,
                            IsActive = true,
                            Name = "Nadia Jamil"
                        },
                        new
                        {
                            Id = 18,
                            City = "Quetta",
                            Course = "BSCS",
                            Email = "shahid@student.com",
                            EnrollDate = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 1.8999999999999999,
                            IsActive = true,
                            Name = "Shahid Afridi"
                        },
                        new
                        {
                            Id = 19,
                            City = "Lahore",
                            Course = "BBA",
                            Email = "alishba@student.com",
                            EnrollDate = new DateTime(2024, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.0,
                            IsActive = true,
                            Name = "Alishba Akhtar"
                        },
                        new
                        {
                            Id = 20,
                            City = "Karachi",
                            Course = "BSIT",
                            Email = "haris@student.com",
                            EnrollDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.2999999999999998,
                            IsActive = true,
                            Name = "Haris Malik"
                        },
                        new
                        {
                            Id = 21,
                            City = "Islamabad",
                            Course = "BSCS",
                            Email = "eman@student.com",
                            EnrollDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.1499999999999999,
                            IsActive = true,
                            Name = "Eman Fatima"
                        },
                        new
                        {
                            Id = 22,
                            City = "Multan",
                            Course = "BSIT",
                            Email = "raza@student.com",
                            EnrollDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.8500000000000001,
                            IsActive = true,
                            Name = "Raza Haider"
                        },
                        new
                        {
                            Id = 23,
                            City = "Faisalabad",
                            Course = "BBA",
                            Email = "iqra@student.com",
                            EnrollDate = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.25,
                            IsActive = true,
                            Name = "Iqra Nasir"
                        },
                        new
                        {
                            Id = 24,
                            City = "Rawalpindi",
                            Course = "BSCS",
                            Email = "danish@student.com",
                            EnrollDate = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.0,
                            IsActive = true,
                            Name = "Danish Raza"
                        },
                        new
                        {
                            Id = 25,
                            City = "Peshawar",
                            Course = "BSIT",
                            Email = "hira@student.com",
                            EnrollDate = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.0499999999999998,
                            IsActive = true,
                            Name = "Hira Batool"
                        },
                        new
                        {
                            Id = 26,
                            City = "Quetta",
                            Course = "BBA",
                            Email = "mohsin@student.com",
                            EnrollDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.4500000000000002,
                            IsActive = true,
                            Name = "Mohsin Ali"
                        },
                        new
                        {
                            Id = 27,
                            City = "Lahore",
                            Course = "BSCS",
                            Email = "sadia@student.com",
                            EnrollDate = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.3500000000000001,
                            IsActive = true,
                            Name = "Sadia Anwar"
                        },
                        new
                        {
                            Id = 28,
                            City = "Karachi",
                            Course = "BSIT",
                            Email = "sufyan@student.com",
                            EnrollDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.1499999999999999,
                            IsActive = true,
                            Name = "Sufyan Ahmed"
                        },
                        new
                        {
                            Id = 29,
                            City = "Islamabad",
                            Course = "BBA",
                            Email = "aleena@student.com",
                            EnrollDate = new DateTime(2024, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.75,
                            IsActive = true,
                            Name = "Aleena Khan"
                        },
                        new
                        {
                            Id = 30,
                            City = "Multan",
                            Course = "BSCS",
                            Email = "hassanr@student.com",
                            EnrollDate = new DateTime(2024, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 1.8,
                            IsActive = true,
                            Name = "Hassan Raza"
                        },
                        new
                        {
                            Id = 31,
                            City = "Faisalabad",
                            Course = "BSIT",
                            Email = "mariam@student.com",
                            EnrollDate = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.5,
                            IsActive = true,
                            Name = "Mariam Asif"
                        },
                        new
                        {
                            Id = 32,
                            City = "Rawalpindi",
                            Course = "BBA",
                            Email = "taha@student.com",
                            EnrollDate = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.2000000000000002,
                            IsActive = true,
                            Name = "Taha Ahmed"
                        },
                        new
                        {
                            Id = 33,
                            City = "Peshawar",
                            Course = "BSCS",
                            Email = "mehak@student.com",
                            EnrollDate = new DateTime(2024, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.9500000000000002,
                            IsActive = true,
                            Name = "Mehak Aslam"
                        },
                        new
                        {
                            Id = 34,
                            City = "Quetta",
                            Course = "BSIT",
                            Email = "usamac@student.com",
                            EnrollDate = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.6000000000000001,
                            IsActive = true,
                            Name = "Usama Chaudhry"
                        },
                        new
                        {
                            Id = 35,
                            City = "Lahore",
                            Course = "BBA",
                            Email = "hania@student.com",
                            EnrollDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.6000000000000001,
                            IsActive = true,
                            Name = "Hania Aamir"
                        });
                });

            modelBuilder.Entity("StudentAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            Name = "Admin",
                            PasswordHash = "$2b$11$Glz.i7DzU/P8b4/9n/Hwc.EndWg4drs7VofW3FEM4/5GghBZrYdwG",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "abdullah@gmail.com",
                            Name = "abdullah",
                            PasswordHash = "$2b$11$Glz.i7DzU/P8b4/9n/Hwc.EndWg4drs7VofW3FEM4/5GghBZrYdwG",
                            Role = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
