// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAPI.Data;

#nullable disable

namespace StudentAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831221737_UpdateSeedUserPasswords")]
    partial class UpdateSeedUserPasswords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentAPI.Models.AcademicClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Program", "Semester", "Section", "Session")
                        .IsUnique();

                    b.ToTable("AcademicClasses");
                });

            modelBuilder.Entity("StudentAPI.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("LectureDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MarkedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId", "StudentId", "LectureDate")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("StudentAPI.Models.ClassEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("AcademicClassId", "StudentId")
                        .IsUnique();

                    b.ToTable("ClassEnrollments");
                });

            modelBuilder.Entity("StudentAPI.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicClassId")
                        .HasColumnType("int");

                    b.Property<decimal>("DefaultTotalMarks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AcademicClassId", "Name")
                        .IsUnique();

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("StudentAPI.Models.MarkRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExamId")
                        .HasColumnType("int");

                    b.Property<decimal>("ObtainedMarks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalMarks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("MarkRecords");
                });

            modelBuilder.Entity("StudentAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EnrollDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Lahore",
                            Course = "BSIT",
                            Email = "abdullah@student.com",
                            EnrollDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.9500000000000002,
                            IsActive = true,
                            Name = "Abdullah Imran"
                        },
                        new
                        {
                            Id = 2,
                            City = "Karachi",
                            Course = "BSCS",
                            Email = "ali@student.com",
                            EnrollDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.7000000000000002,
                            IsActive = true,
                            Name = "Ali Hassan"
                        },
                        new
                        {
                            Id = 3,
                            City = "Lahore",
                            Course = "BSIT",
                            Email = "sara@student.com",
                            EnrollDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.8500000000000001,
                            IsActive = true,
                            Name = "Sara Khan"
                        },
                        new
                        {
                            Id = 4,
                            City = "Islamabad",
                            Course = "BBA",
                            Email = "usman@student.com",
                            EnrollDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.6000000000000001,
                            IsActive = true,
                            Name = "Usman Malik"
                        },
                        new
                        {
                            Id = 5,
                            City = "Karachi",
                            Course = "BSCS",
                            Email = "ayesha@student.com",
                            EnrollDate = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.8999999999999999,
                            IsActive = true,
                            Name = "Ayesha Siddiqui"
                        },
                        new
                        {
                            Id = 6,
                            City = "Multan",
                            Course = "BSIT",
                            Email = "bilal@student.com",
                            EnrollDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.3999999999999999,
                            IsActive = true,
                            Name = "Bilal Ahmed"
                        },
                        new
                        {
                            Id = 7,
                            City = "Faisalabad",
                            Course = "BSCS",
                            Email = "fatima@student.com",
                            EnrollDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.5499999999999998,
                            IsActive = true,
                            Name = "Fatima Noor"
                        },
                        new
                        {
                            Id = 8,
                            City = "Rawalpindi",
                            Course = "BSIT",
                            Email = "hamza@student.com",
                            EnrollDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.7999999999999998,
                            IsActive = true,
                            Name = "Hamza Ali"
                        },
                        new
                        {
                            Id = 9,
                            City = "Peshawar",
                            Course = "BBA",
                            Email = "zara@student.com",
                            EnrollDate = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.1000000000000001,
                            IsActive = true,
                            Name = "Zara Ahmed"
                        },
                        new
                        {
                            Id = 10,
                            City = "Quetta",
                            Course = "BSIT",
                            Email = "omar@student.com",
                            EnrollDate = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.3999999999999999,
                            IsActive = true,
                            Name = "Omar Farooq"
                        },
                        new
                        {
                            Id = 11,
                            City = "Lahore",
                            Course = "BSCS",
                            Email = "hina@student.com",
                            EnrollDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.8999999999999999,
                            IsActive = true,
                            Name = "Hina Rizvi"
                        },
                        new
                        {
                            Id = 12,
                            City = "Karachi",
                            Course = "BSIT",
                            Email = "rayan@student.com",
                            EnrollDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.2000000000000002,
                            IsActive = true,
                            Name = "Rayan Khan"
                        },
                        new
                        {
                            Id = 13,
                            City = "Islamabad",
                            Course = "BBA",
                            Email = "mahnoor@student.com",
                            EnrollDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.1000000000000001,
                            IsActive = true,
                            Name = "Mahnoor Sheikh"
                        },
                        new
                        {
                            Id = 14,
                            City = "Multan",
                            Course = "BSCS",
                            Email = "zain@student.com",
                            EnrollDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.2999999999999998,
                            IsActive = true,
                            Name = "Zain Abbas"
                        },
                        new
                        {
                            Id = 15,
                            City = "Faisalabad",
                            Course = "BSIT",
                            Email = "sana@student.com",
                            EnrollDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.7000000000000002,
                            IsActive = true,
                            Name = "Sana Tariq"
                        },
                        new
                        {
                            Id = 16,
                            City = "Rawalpindi",
                            Course = "BBA",
                            Email = "adeel@student.com",
                            EnrollDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.5800000000000001,
                            IsActive = true,
                            Name = "Adeel Hussain"
                        },
                        new
                        {
                            Id = 17,
                            City = "Peshawar",
                            Course = "BSIT",
                            Email = "nadia@student.com",
                            EnrollDate = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.5,
                            IsActive = true,
                            Name = "Nadia Jamil"
                        },
                        new
                        {
                            Id = 18,
                            City = "Quetta",
                            Course = "BSCS",
                            Email = "shahid@student.com",
                            EnrollDate = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 1.8999999999999999,
                            IsActive = true,
                            Name = "Shahid Afridi"
                        },
                        new
                        {
                            Id = 19,
                            City = "Lahore",
                            Course = "BBA",
                            Email = "alishba@student.com",
                            EnrollDate = new DateTime(2024, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.0,
                            IsActive = true,
                            Name = "Alishba Akhtar"
                        },
                        new
                        {
                            Id = 20,
                            City = "Karachi",
                            Course = "BSIT",
                            Email = "haris@student.com",
                            EnrollDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.2999999999999998,
                            IsActive = true,
                            Name = "Haris Malik"
                        },
                        new
                        {
                            Id = 21,
                            City = "Islamabad",
                            Course = "BSCS",
                            Email = "eman@student.com",
                            EnrollDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.1499999999999999,
                            IsActive = true,
                            Name = "Eman Fatima"
                        },
                        new
                        {
                            Id = 22,
                            City = "Multan",
                            Course = "BSIT",
                            Email = "raza@student.com",
                            EnrollDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.8500000000000001,
                            IsActive = true,
                            Name = "Raza Haider"
                        },
                        new
                        {
                            Id = 23,
                            City = "Faisalabad",
                            Course = "BBA",
                            Email = "iqra@student.com",
                            EnrollDate = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.25,
                            IsActive = true,
                            Name = "Iqra Nasir"
                        },
                        new
                        {
                            Id = 24,
                            City = "Rawalpindi",
                            Course = "BSCS",
                            Email = "danish@student.com",
                            EnrollDate = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.0,
                            IsActive = true,
                            Name = "Danish Raza"
                        },
                        new
                        {
                            Id = 25,
                            City = "Peshawar",
                            Course = "BSIT",
                            Email = "hira@student.com",
                            EnrollDate = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.0499999999999998,
                            IsActive = true,
                            Name = "Hira Batool"
                        },
                        new
                        {
                            Id = 26,
                            City = "Quetta",
                            Course = "BBA",
                            Email = "mohsin@student.com",
                            EnrollDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.4500000000000002,
                            IsActive = true,
                            Name = "Mohsin Ali"
                        },
                        new
                        {
                            Id = 27,
                            City = "Lahore",
                            Course = "BSCS",
                            Email = "sadia@student.com",
                            EnrollDate = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.3500000000000001,
                            IsActive = true,
                            Name = "Sadia Anwar"
                        },
                        new
                        {
                            Id = 28,
                            City = "Karachi",
                            Course = "BSIT",
                            Email = "sufyan@student.com",
                            EnrollDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.1499999999999999,
                            IsActive = true,
                            Name = "Sufyan Ahmed"
                        },
                        new
                        {
                            Id = 29,
                            City = "Islamabad",
                            Course = "BBA",
                            Email = "aleena@student.com",
                            EnrollDate = new DateTime(2024, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.75,
                            IsActive = true,
                            Name = "Aleena Khan"
                        },
                        new
                        {
                            Id = 30,
                            City = "Multan",
                            Course = "BSCS",
                            Email = "hassanr@student.com",
                            EnrollDate = new DateTime(2024, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 1.8,
                            IsActive = true,
                            Name = "Hassan Raza"
                        },
                        new
                        {
                            Id = 31,
                            City = "Faisalabad",
                            Course = "BSIT",
                            Email = "mariam@student.com",
                            EnrollDate = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.5,
                            IsActive = true,
                            Name = "Mariam Asif"
                        },
                        new
                        {
                            Id = 32,
                            City = "Rawalpindi",
                            Course = "BBA",
                            Email = "taha@student.com",
                            EnrollDate = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.2000000000000002,
                            IsActive = true,
                            Name = "Taha Ahmed"
                        },
                        new
                        {
                            Id = 33,
                            City = "Peshawar",
                            Course = "BSCS",
                            Email = "mehak@student.com",
                            EnrollDate = new DateTime(2024, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.9500000000000002,
                            IsActive = true,
                            Name = "Mehak Aslam"
                        },
                        new
                        {
                            Id = 34,
                            City = "Quetta",
                            Course = "BSIT",
                            Email = "usamac@student.com",
                            EnrollDate = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 2.6000000000000001,
                            IsActive = true,
                            Name = "Usama Chaudhry"
                        },
                        new
                        {
                            Id = 35,
                            City = "Lahore",
                            Course = "BBA",
                            Email = "hania@student.com",
                            EnrollDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GPA = 3.6000000000000001,
                            IsActive = true,
                            Name = "Hania Aamir"
                        });
                });

            modelBuilder.Entity("StudentAPI.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicClassId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TeacherUserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("AcademicClassId", "Code")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("StudentAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            IsApproved = true,
                            Name = "Admin",
                            PasswordHash = "$2b$12$ozwluGM8jahSdFWdlXti3ejmtFyL2ImvmjmwMSBd3gYDwJHwLHhF6",
                            Phone = "",
                            RequestedRole = "Admin",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "abdullah58rajput@gmail.com",
                            IsApproved = true,
                            Name = "abdullah",
                            PasswordHash = "$2b$12$ozwluGM8jahSdFWdlXti3ejmtFyL2ImvmjmwMSBd3gYDwJHwLHhF6",
                            Phone = "",
                            RequestedRole = "Admin",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("StudentAPI.Models.AttendanceRecord", b =>
                {
                    b.HasOne("StudentAPI.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentAPI.Models.Subject", "Subject")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentAPI.Models.ClassEnrollment", b =>
                {
                    b.HasOne("StudentAPI.Models.AcademicClass", "AcademicClass")
                        .WithMany("Enrollments")
                        .HasForeignKey("AcademicClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentAPI.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicClass");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentAPI.Models.Exam", b =>
                {
                    b.HasOne("StudentAPI.Models.AcademicClass", "AcademicClass")
                        .WithMany()
                        .HasForeignKey("AcademicClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicClass");
                });

            modelBuilder.Entity("StudentAPI.Models.MarkRecord", b =>
                {
                    b.HasOne("StudentAPI.Models.Exam", "Exam")
                        .WithMany("MarkRecords")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentAPI.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentAPI.Models.Subject", "Subject")
                        .WithMany("MarkRecords")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentAPI.Models.Subject", b =>
                {
                    b.HasOne("StudentAPI.Models.AcademicClass", "AcademicClass")
                        .WithMany("Subjects")
                        .HasForeignKey("AcademicClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentAPI.Models.User", "TeacherUser")
                        .WithMany()
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudentAPI.Models.User", null)
                        .WithMany("TeachingSubjects")
                        .HasForeignKey("UserId");

                    b.Navigation("AcademicClass");

                    b.Navigation("TeacherUser");
                });

            modelBuilder.Entity("StudentAPI.Models.AcademicClass", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudentAPI.Models.Exam", b =>
                {
                    b.Navigation("MarkRecords");
                });

            modelBuilder.Entity("StudentAPI.Models.Subject", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("MarkRecords");
                });

            modelBuilder.Entity("StudentAPI.Models.User", b =>
                {
                    b.Navigation("TeachingSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
