import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AcademicService, MyAttendance, MyResults } from '../../services/academic.service';

@Component({selector:'app-student-academic',standalone:true,imports:[CommonModule],template:`
<div class="workspace"><div class="topbar"><div><span class="eyebrow">MY ACADEMIC PORTAL</span><h2>Results & attendance</h2><p>Your account is read-only. Only your own published academic information is visible.</p></div><button class="ghost" (click)="load()">↻ Refresh</button></div>
<div class="notice error" *ngIf="error">{{error}}</div>
<section class="stats"><article class="card"><span>Current GPA</span><b>{{results?.gpa||0|number:'1.1-2'}}</b><small>Based on published results</small></article><article class="card"><span>Subjects with marks</span><b>{{results?.subjects?.length||0}}</b><small>Published/available records</small></article><article class="card"><span>Attendance subjects</span><b>{{attendance.length}}</b><small>Recorded attendance</small></article></section>
<section class="card panel"><div class="section-head"><div><span class="eyebrow">RESULTS</span><h3>{{results?.name||'Student result'}}</h3></div></div><div class="table"><div class="thead"><span>Exam</span><span>Subject</span><span>Marks</span><span>Grade</span><span>GPA</span></div><div class="tr" *ngFor="let r of results?.subjects"><span>{{r.examName}}</span><span><b>{{r.subjectName}}</b><small>{{r.code}} · {{r.creditHours}} credits</small></span><span>{{r.obtainedMarks}} / {{r.totalMarks}}<small>{{r.percent}}%</small></span><strong>{{r.grade}}</strong><span>{{r.point|number:'1.1-1'}}</span></div><p class="muted" *ngIf="!results?.subjects?.length">No published results are available yet.</p></div></section>
<section class="card panel"><div class="section-head"><div><span class="eyebrow">ATTENDANCE</span><h3>Subject-wise attendance</h3></div></div><div class="attendance" *ngFor="let a of attendance"><div><b>{{a.name}}</b><small>{{a.code}}</small></div><strong [class.bad]="a.attendancePercent<75">{{a.attendancePercent|number:'1.0-2'}}%</strong><span>{{a.present}} present · {{a.absent}} absent · {{a.totalLectures}} recorded</span><div class="bar"><i [style.width.%]="a.attendancePercent"></i></div></div><p class="muted" *ngIf="!attendance.length">No attendance records are available yet.</p></section>
</div>`,styles:[`.workspace{padding-bottom:40px}.topbar{display:flex;justify-content:space-between;margin-bottom:18px}.topbar h2{margin:4px 0;font-size:26px}.topbar p{margin:0;color:#718097;font-size:12px}.eyebrow{font-size:10px;letter-spacing:1.4px;color:#6686a5;font-weight:800}.ghost{border:1px solid #dce6f0;background:white;border-radius:10px;padding:10px 13px;height:max-content;cursor:pointer}.card{background:rgba(255,255,255,.9);border:1px solid #e3ebf3;border-radius:18px;box-shadow:0 12px 30px rgba(40,65,95,.06);transition:box-shadow .2s ease}.panel{padding:18px;margin-top:16px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.stats article{padding:16px}.stats span,.stats small{display:block;color:#708098;font-size:11px}.stats b{display:block;font-size:28px;margin:7px 0}.section-head{display:flex;justify-content:space-between}.section-head h3{margin:4px 0 12px}.table{display:grid}.thead,.tr{display:grid;grid-template-columns:1.1fr 1.5fr 1fr .65fr .55fr;gap:10px;align-items:center;padding:11px 7px;border-bottom:1px solid #edf2f7;font-size:11px}.thead{font-size:10px;text-transform:uppercase;letter-spacing:.6px;color:#8492a1;font-weight:800}.tr span small,.tr span b{display:block}.tr span small{font-size:10px;color:#7e8d9f;margin-top:3px}.tr strong{color:#287a68}.attendance{display:grid;grid-template-columns:1.2fr 90px 1.3fr 1fr;gap:12px;align-items:center;padding:13px 5px;border-bottom:1px solid #eef3f7}.attendance b,.attendance small{display:block}.attendance small{font-size:10px;color:#7e8d9f;margin-top:3px}.attendance strong{text-align:right;font-size:15px}.attendance>span{font-size:10px;color:#7e8d9f}.bar{height:7px;background:#edf2f7;border-radius:20px;overflow:hidden}.bar i{display:block;height:100%;background:linear-gradient(90deg,#32cfc7,#648df5);border-radius:20px}.bad{color:#b44759}.muted{color:#8996a6;font-size:12px}@media(max-width:800px){.stats{grid-template-columns:1fr}.thead,.tr{grid-template-columns:1fr 1fr}.thead span:nth-child(n+3),.tr>span:nth-child(n+3),.tr strong{margin-top:5px}.attendance{grid-template-columns:1fr 80px}.attendance>span,.attendance .bar{grid-column:1/-1}}button{transition:transform .15s ease,box-shadow .15s ease,filter .15s ease,background .15s ease,color .15s ease,border-color .15s ease}.ghost:hover{background:#f3f8fc;border-color:#a9c3da;box-shadow:0 4px 12px rgba(40,80,120,.1);transform:translateY(-1px)}.ghost:active{transform:translateY(0)}.card:hover{box-shadow:0 16px 36px rgba(40,65,95,.09)}`]
})
export class StudentAcademicComponent implements OnInit {
  results:MyResults|null=null;attendance:MyAttendance[]=[];error='';constructor(private api:AcademicService){}ngOnInit(){this.load()}load(){this.api.myResults().subscribe({next:x=>this.results=x,error:e=>this.fail(e)});this.api.myAttendance().subscribe({next:x=>this.attendance=x,error:e=>this.fail(e)})}fail(e:any){
    if(e?.error?.message) this.error=e.error.message;
    else if(typeof e?.error==='string' && e.error.trim()) this.error=e.error;
    else if(e?.error?.errors) this.error=Object.values(e.error.errors).flat().join(' ');
    else if(e?.status===0) this.error='Could not reach the server. Check your connection and that the API is running.';
    else if(e?.message) this.error=e.message;
    else this.error='Could not load your academic data.';
  }}
